### ISSUE TITLE
Flutter sdk does not respect  datachannel limit of 64Kb 

### ISSUE THREAD

**Issue by eugenechyrski** [viamrobotics/viam-flutter-sdk#161]
https://github.com/viamrobotics/viam-flutter-sdk/blob/1f89feded83c1267198146a3689952133422e6bf/lib/src/rpc/web_rtc/web_rtc_transport_stream.dart#L50

Regardless of the size of incoming message single PacketMessage is created which causes delivery issues(messages over 64kb are not delivered).

**Comment by njooma** [comment]
Hi, thanks for filing this ticket. The issue should be fixed with the release of version [v0.0.11](https://github.com/viamrobotics/viam-flutter-sdk/releases/tag/v0.0.11). 

Please reopen if the issue persists. Thanks!
